services:
  scoutr:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '5055:5055'
    environment:
      DB_TYPE: 'postgres' # Scoutr's default DB engine. Set to "sqlite" (see compose.sqlite.yaml) to opt out
      DB_HOST: 'postgres' # The host (url) of the database
      DB_PORT: '5432' # The port to connect to
      DB_USER: 'scoutr' # Username used to connect to the database
      DB_PASS: 'scoutr' # Password of the user used to connect to the database
      DB_NAME: 'scoutr' # The name of the database to connect to
      DB_LOG_QUERIES: 'false' # Whether to log the DB queries for debugging
      DB_USE_SSL: 'false' # Whether to enable ssl for database connection
      DB_POOL_SIZE: '10' # The number of connections to maintain in the connection pool
    volumes:
      - .:/app:rw,cached
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: scoutr
      POSTGRES_PASSWORD: scoutr
      POSTGRES_DB: scoutr
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql
volumes:
  postgres:
